### ISSUE TITLE
Create gain-related methods

### ISSUE THREAD

**Issue by DavidWz** [kperun/SATPrakPDW#3]
In order to chose a contraction candidate, we need to calculate gain.
So add a method to ICPContractionCandidate which calculates its gain (relying on getContractedInterval).
Also add a method to ICPState which returns the best contraction candidate.

**Comment by kperun** [comment]
I take this one. It should be quite easy to compute the gain by utilizing the contraction candidate and its getContratedIntervall together with an assisting method.

**Comment by kperun** [comment]
computeGain() implemented, it expects a contraction candidate and a interval map in order to compute the new interval, but also to retrieve the old one from the map.

**Comment by kperun** [comment]
getBestContractionCandidate() implemented and tested. Issue closed.

**Comment by kperun** [comment]
A small fix is still required: if an empty vector of candidates is provided, what is the intended behavior in getBestContractionCandidate(), @DavidWz ?

**Comment by DavidWz** [comment]
@kperun 
getBestContractionCandidate still doesn't seem to work.
If you run the example /bounded/meti-tarski_bounded/polypaver-bench-sqrt-3d-chunk-0017.smt2 
you can see how it picks the same contraction candidate over and over again until the maximal number of iterations is reached. even though there are better candidates, i.e. skoY and skoZ

**Comment by kperun** [comment]
@DavidWz I have partially updated the method. Now it also takes into account strict and weak interval boundaries. However, we have to consider several other things, e.g. whenever the old interval [-1000,1000] is split to [-1000,0] and [0,1000], what is the gain of this interval? The problem here is that the new interval has in total the same diameter as the old one, resulting in the situation as you already mentioned (e.g. as occurring in polypaver-bench-sqrt-3d-chunk-0017.smt2). Here,further discussion is required.
