### ISSUE TITLE
Make the list of leave nodes a priority queue

### ISSUE THREAD

**Issue by Verdict7** [kperun/SATPrakPDW#35]
Right now we only push new child trees onto a stack, the last child that is created is expanded first.
This can be improved by using a priority queue for the trees, and sorting them by some heuristic, e.g. the number of constraints that are already fulfilled when guessing a solution.

**Comment by kperun** [comment]
@Verdict7 this has been partially implemented in 6177bd3. However, currently it behaves like a normal vector since no comparison operator has been implemented. Here, some discussion is required. A method which compares two ICPTrees based on the number of solved constraints is also partially implemented, but not yet complete.

**Comment by kperun** [comment]
@Verdict7 , @DavidWz  issue has been solved. Now, the internal structure storing all leaf nodes which have to be processed is represented by means of a priority queue. On first glance, it reduces the number of nodes which have to be checked by about  30 % (in tested examples from 6 nodes to 4). However, here more testing (maybe on bigger examples) is required. Please review the code and close the issue.
