### ISSUE TITLE
Benchmarking Suite

### ISSUE THREAD

**Issue by Verdict7** [kperun/SATPrakPDW#42]
We are getting to the point where we want to compare heuristics and statistics. 
We should take a look at available smt problems, and start benchmarking (e.g. linearization, average time for propagation, etc.). 
Specifically:
Find some suitable tests.
Come up with and implement a method to time specific functions. 
Maybe come up with a method to switch heuristic functions in an efficient way (switch case?) to make testing easier.

**Comment by Verdict7** [comment]
Also maybe create a testing suite, with a number of tests that have a known answer.
Create a bash script or similar that runs the tests and checks if the answer is correct.

**Comment by DavidWz** [comment]
The sat solver itself will check if the answer is correct.
If the given file it runs on has a (set-info :status un/sat) and our ICP module returns a value different from that, the final output of the SAT solver will be (error "expected un/sat, but returned un/sat") instead of simply "sat" or "unsat".

So the testing suite actually just has to call our solver with a bunch of example files that have the set-info status set and complain if the output is "error".

**Comment by kperun** [comment]
I will take a look at this and write a bash script doing this stuff.

**Comment by kperun** [comment]
@DavidWz  added in the latest push. Script has to be located in the smtrat folder and can be executed by means of "./benchmark PATH_TO_FOLDER_WITH_MODELS".
